### PR TITLE
fix/10.0.2.46689

### PR DESCRIPTION
**Pull request by vidalj13**
fix/10.0.2.46689

### CODE REVIEW

**Comment by vidalj13** [comment]
not for me without this since yesterday, and i see same on curse :
https://www.curseforge.com/wow/addons/buyemall
[image: image.png]
and
[image: image.png]

Le jeu. 17 nov. 2022 à 11:15, Rowan Freeman ***@***.***> a
écrit :

**Comment by rowanfreeman** [comment]
Sorry, just to confirm, I was approving your PR :) Your PR works for me on live, and the addon is broken without it 😁

**Comment by vidalj13** [comment]
Ho ok :) thanks, it's nor me  it's fuba82 :) i just commit he's fix :)

Le jeu. 17 nov. 2022 à 11:29, Rowan Freeman ***@***.***> a
écrit :

**Review by J141 — APPROVED** [review]
Looks good. I'll merge it in and release the update in an hour or once I'm home. Thanks for this! :)

**Pull request merged**
